#!/bin/bash
set -euo pipefail

# This script is running update_decks.sh

PROJECT_DIR="$HOME/Documents/dpd-db"
cd "$PROJECT_DIR" || exit 1

answer=$(uv run tools/ask.py "Do you want to attempt to mount the fileserver?") || exit 1
if [[ $answer == "y" ]]; then
    mnt
fi

uv run bash scripts/bash/update_decks.sh

answer=$(uv run tools/ask.py "Do you want to umount the fileserver?") || exit 1
if [[ $answer == "y" ]]; then
    umnt
fi