#!/bin/bash

# This script is a wrapper for run_and_log.sh
# It executes scripts/bash/make_dpd.sh or make_ru_dpd.sh or copy_dpd_to_server with logging and rotation.

# Determine the directory of this script
PROJECT_ROOT="$HOME/Documents/dpd-db"

MASTER_SCRIPT="$HOME/.local/bin/run_and_log.sh"

LOG_BASE_NAME="make_dpd"
TARGET_SCRIPT_PATH="${PROJECT_ROOT}/scripts/bash/make_dpd.sh"
TARGET_SCRIPT_PATH_RU="${PROJECT_ROOT}/scripts/bash/make_ru_dpd.sh"
TARGET_SCRIPT_PATH_COPY="${PROJECT_ROOT}/scripts/bash/copy_dpd_to_server"
TARGET_SCRIPT_PATH_COPY_TPR="${PROJECT_ROOT}/scripts/moving/copy_dpd_for_classes.py"

# The command to run, including 'uv run bash'
COMMAND_TO_EXECUTE=(bash -c "cd '${PROJECT_ROOT}' && uv run bash '${TARGET_SCRIPT_PATH}'")
COMMAND_TO_EXECUTE_RU=(bash -c "cd '${PROJECT_ROOT}' && uv run bash '${TARGET_SCRIPT_PATH_RU}'")
COMMAND_TO_EXECUTE_COPY=(bash -c "cd '${PROJECT_ROOT}' && uv run bash '${TARGET_SCRIPT_PATH_COPY}'")
COMMAND_TO_EXECUTE_COPY_TPR=(bash -c "cd '${PROJECT_ROOT}' && uv run python '${TARGET_SCRIPT_PATH_COPY_TPR}'")

# Execute the master script

while true; do
    echo -ne "\033[1;34m make DPD? \033[0m"
    read -n 1 -s user_input
    echo
    if [[ $user_input == "q" ]]; then
        echo -e "\n\033[1;31m Aborted by user.\033[0m"
        exit 1
    fi
    case $user_input in
        [Yy]* )
            bash "${MASTER_SCRIPT}" "${LOG_BASE_NAME}" "${COMMAND_TO_EXECUTE[@]}"
            break;;
        * )
            break;;
    esac
done

while true; do
    echo -ne "\033[1;34m make RU-DPD? \033[0m"
    read -n 1 -s user_input
    echo
    if [[ $user_input == "q" ]]; then
        echo -e "\n\033[1;31m Aborted by user.\033[0m"
        exit 1
    fi
    case $user_input in
        [Yy]* )
            bash "${MASTER_SCRIPT}" "${LOG_BASE_NAME}" "${COMMAND_TO_EXECUTE_RU[@]}"
            break;;
        * )
            break;;
    esac
done

# Ask the user if they want to attempt to mount the fileserver
while true; do
    echo -ne "\033[1;34m Do you want to attempt to mount the fileserver? \033[0m"
    read mount_confirm
    case $mount_confirm in
        [Yy]* )
            mnt
            break;;
        * )
            break;;
    esac
done

while true; do
    echo -ne "\033[1;34m copy DPD+SBS to the /Sharing between users/1 For Everyone/Software/Golden Dictionary/Default folder? \033[0m"
    read -n 1 -s user_input
    echo
    if [[ $user_input == "q" ]]; then
        echo -e "\n\033[1;31m Aborted by user.\033[0m"
        exit 1
    fi
    case $user_input in
        [Yy]* )
            bash "${MASTER_SCRIPT}" "${LOG_BASE_NAME}" "${COMMAND_TO_EXECUTE_COPY[@]}"
            break;;
        * )
            break;;
    esac
done

while true; do
    echo -ne "\033[1;34m copy DPD + TPR for class to the /Sharing between users/For A Deva/for_classes/ folder? \033[0m"
    read -n 1 -s user_input
    echo
    if [[ $user_input == "q" ]]; then
        echo -e "\n\033[1;31m Aborted by user.\033[0m"
        exit 1
    fi
    case $user_input in
        [Yy]* )
            bash "${MASTER_SCRIPT}" "${LOG_BASE_NAME}" "${COMMAND_TO_EXECUTE_COPY_TPR[@]}"
            break;;
        * )
            break;;
    esac
done

# Ask the user if they want to attempt to umount the fileserver
while true; do
    echo -ne "\033[1;34m Do you want to umount the fileserver? \033[0m"
    read -n 1 -s mount_confirm
    if [[ $mount_confirm == "q" ]]; then
        echo -e "\n\033[1;31m Aborted by user.\033[0m"
        exit 1
    fi
    case $mount_confirm in
        [Yy]* )
            umnt
            break;;
        * )
            break;;
    esac
done