"""SBS Anki deck configuration and expected collection snapshot."""

import datetime
import re
from dataclasses import dataclass
from typing import Any, Callable, Literal

from db.models import DpdHeadword
from tools.sbs_table_functions import SBS_table_tools

current_date: str = datetime.date.today().strftime("%m-%d")
_SBS_TOOLS: SBS_table_tools = SBS_table_tools()


@dataclass
class DeckSpec:
    deck_name: str
    model_name: str
    csv_path_attr: str  # Path relative to dpspth.anki_csvs_dir or similar
    slug: str  # For .apkg filename
    source: Literal["db", "csv"]
    field_map: dict[str, Callable[[Any], str]]
    updates_tags: bool = False
    creates_new_notes: bool = True


def _to_br(text: str | None) -> str:
    return text.replace("\n", "<br>") if text else ""


# --- Producers for field_map ---

sbs_ped_link: str = 'Spot a mistake? <a class="link" href="https://docs.google.com/forms/d/e/1FAIpQLScNC5v2gQbBCM3giXfYIib9zrp-WMzwJuf_iVXEMX2re4BFFw/viewform?usp=pp_url&entry.438735500'


def get_feedback(i: DpdHeadword, deck_name: str) -> str:
    return f"""{sbs_ped_link}={i.lemma_1}&entry.1433863141={deck_name.upper()}-{current_date}">Fix it here.</a>"""


def get_root_key(i: DpdHeadword) -> str:
    if i.rt:
        return re.sub(r" \d*$", "", i.root_key)
    return ""


def get_construction(i: DpdHeadword) -> str:
    return _to_br(i.construction)


def get_phonetic(i: DpdHeadword) -> str:
    return _to_br(i.phonetic)


def get_paritta_source(i: DpdHeadword) -> tuple[str, str, str]:
    chant_names = ["Karaṇīya-metta-sutta", "Ratana-sutta", "Maṅgala-sutta"]
    if not i.sbs:
        return "", "", ""
    sbs_sources = [i.sbs.sbs_source_1, i.sbs.sbs_source_2]
    sbs_suttas = [i.sbs.sbs_sutta_1, i.sbs.sbs_sutta_2]
    sbs_examples = [i.sbs.sbs_example_1, i.sbs.sbs_example_2]
    sbs_palichants = [i.sbs.sbs_chant_pali_1, i.sbs.sbs_chant_pali_2]

    for source, sutta, example, palichant in zip(
        sbs_sources, sbs_suttas, sbs_examples, sbs_palichants
    ):
        if any(chant_name in palichant for chant_name in chant_names):
            return (_to_br(source), _to_br(sutta), _to_br(example))
    return "", "", ""


def get_example_for_class(i: DpdHeadword) -> tuple[str, str, str]:
    if not i.sbs:
        return "", "", ""
    sbs = i.sbs
    sources_priority = [
        ("class_source", "class_sutta", "class_example"),
        ("sbs_source_1", "sbs_sutta_1", "sbs_example_1"),
        ("sbs_source_2", "sbs_sutta_2", "sbs_example_2"),
        ("dhp_source", "dhp_sutta", "dhp_example"),
        ("pat_source", "pat_sutta", "pat_example"),
        ("vib_source", "vib_sutta", "vib_example"),
        ("discourses_source", "discourses_sutta", "discourses_example"),
    ]
    for src_attr, sut_attr, ex_attr in sources_priority:
        example_val = getattr(sbs, ex_attr, None)
        if example_val:
            source_val = getattr(sbs, src_attr, None)
            sutta_val = getattr(sbs, sut_attr, None)
            return (_to_br(source_val), _to_br(sutta_val), _to_br(example_val))
    if i.source_1:
        return (_to_br(i.source_1), _to_br(i.sutta_1), _to_br(i.example_1))
    return "", "", ""


def _base_db_fields() -> dict[str, Callable[[DpdHeadword], str]]:
    """Field lambdas shared across all DB-sourced decks; unique fields override or extend."""
    return {
        "id": lambda i: str(i.id),
        "pali": lambda i: i.lemma_1,
        "grammar": lambda i: i.grammar,
        "neg": lambda i: i.neg,
        "verb": lambda i: i.verb,
        "trans": lambda i: i.trans,
        "plus_case": lambda i: i.plus_case,
        "meaning": lambda i: i.meaning_1 or i.meaning_2,
        "meaning_lit": lambda i: i.meaning_lit,
        "native": lambda i: "",
        "sanskrit": lambda i: i.sanskrit,
        "sanskrit_root": lambda i: i.rt.sanskrit_root if i.rt else "",
        "sanskrit_root_meaning": lambda i: i.rt.sanskrit_root_meaning if i.rt else "",
        "sanskrit_root_class": lambda i: i.rt.sanskrit_root_class if i.rt else "",
        "root": get_root_key,
        "root_has_verb": lambda i: i.rt.root_has_verb if i.rt else "",
        "root_group": lambda i: str(i.rt.root_group) if i.rt else "",
        "root_sign": lambda i: i.root_sign if i.rt else "",
        "root_meaning": lambda i: i.rt.root_meaning if i.rt else "",
        "root_base": lambda i: i.root_base if i.rt else "",
        "construction": get_construction,
        "derivative": lambda i: i.derivative,
        "suffix": lambda i: i.suffix,
        "phonetic": get_phonetic,
        "compound_type": lambda i: i.compound_type,
        "compound_construction": lambda i: i.compound_construction,
        "antonym": lambda i: i.antonym,
        "synonym": lambda i: i.synonym,
        "variant": lambda i: i.variant,
        "commentary": lambda i: _to_br(i.commentary),
        "notes": lambda i: _to_br(i.notes),
        "link": lambda i: _to_br(i.link),
        "audio": lambda i: _SBS_TOOLS.generate_sbs_audio(i.lemma_clean),
        "test": lambda i: current_date,
    }


# SUTTAS_PREFIX_MAP maps discourses_source prefix -> full subdeck name
SUTTAS_PREFIX_MAP: dict[str, str] = {
    "MN107": "Suttas Advanced Pali Class::1.MN107",
    "SN56": "Suttas Advanced Pali Class::2.SN56",
    "SN22": "Suttas Advanced Pali Class::3.SN22",
    "SN35": "Suttas Advanced Pali Class::4.SN35",
    "SN12": "Suttas Advanced Pali Class::5.SN12",
    "SN47": "Suttas Advanced Pali Class::6.SN47",
    "SN46": "Suttas Advanced Pali Class::7.SN46",
    "SN45": "Suttas Advanced Pali Class::8.SN45",
    "SN43": "Suttas Advanced Pali Class::9.SN43",
}

VOCAB_CLASS_RANGE = range(1, 30)

EXPECTED_COLLECTION: dict[str, dict[str, Any]] = {
    "Common Roots": {
        "model_name": "common roots",
        "fields": [
            "root",
            "root_clean",
            "sanskrit_root",
            "root_group",
            "root_sign",
            "root_meaning",
            "main_verb",
            "examples",
            "native",
            "test",
            "feedback",
            "marks",
        ],
    },
    "Grammar Pali Class": {
        "model_name": "pali class abbrev",
        "fields": [
            "id",
            "abbrev",
            "meaning",
            "pali",
            "example",
            "explanation",
            "type",
            "feedback",
            "test",
            "marks",
        ],
    },
    "Pali Bhikkhu Vibhanga": {
        "model_name": "Vibhanga",
        "fields": [
            "id",
            "pali",
            "grammar",
            "neg",
            "verb",
            "trans",
            "plus_case",
            "meaning",
            "meaning_lit",
            "native",
            "sanskrit",
            "sanskrit_root",
            "sanskrit_root_meaning",
            "sanskrit_root_class",
            "root",
            "root_has_verb",
            "root_group",
            "root_sign",
            "root_meaning",
            "root_base",
            "construction",
            "derivative",
            "suffix",
            "phonetic",
            "compound_type",
            "compound_construction",
            "source",
            "sutta",
            "example",
            "antonym",
            "synonym",
            "variant",
            "commentary",
            "notes",
            "link",
            "audio",
            "test",
            "feedback",
            "marks",
        ],
    },
    "Pali DHP vocab": {
        "model_name": "DHP Vocab",
        "fields": [
            "id",
            "pali",
            "grammar",
            "neg",
            "verb",
            "trans",
            "plus_case",
            "meaning",
            "meaning_lit",
            "native",
            "sanskrit",
            "sanskrit_root",
            "sanskrit_root_meaning",
            "sanskrit_root_class",
            "root",
            "root_has_verb",
            "root_group",
            "root_sign",
            "root_meaning",
            "root_base",
            "construction",
            "derivative",
            "suffix",
            "phonetic",
            "compound_type",
            "compound_construction",
            "source",
            "sutta",
            "example",
            "link",
            "audio",
            "test",
            "feedback",
            "marks",
        ],
    },
    "Pali Parittas": {
        "model_name": "Paritta",
        "fields": [
            "id",
            "pali",
            "grammar",
            "meaning",
            "meaning_lit",
            "root",
            "root_group",
            "root_sign",
            "root_meaning",
            "root_base",
            "construction",
            "source",
            "sutta",
            "example",
            "audio",
            "test",
            "feedback",
            "marks",
        ],
    },
    "Pali Patimokkha Word By Word": {
        "model_name": "Pātimokkha word by word",
        "fields": [
            "pali",
            "pos",
            "grammar",
            "case",
            "native",
            "meaning",
            "meaning_lit",
            "root",
            "root_gp",
            "root_sign",
            "base",
            "construction",
            "compound_type",
            "compound_construction",
            "variant",
            "abbrev",
            "source",
            "sentence",
            "commentary",
            "test",
            "order",
            "feedback",
            "web_link",
            "notez",
        ],
    },
    "Phonetic Changes Pali Class": {
        "model_name": "Phonetic Class",
        "fields": [
            "id",
            "pali",
            "sbs_class_anki",
            "grammar",
            "neg",
            "verb",
            "trans",
            "plus_case",
            "meaning",
            "meaning_lit",
            "native",
            "sanskrit",
            "sanskrit_root",
            "sanskrit_root_meaning",
            "sanskrit_root_class",
            "root",
            "root_has_verb",
            "root_group",
            "root_sign",
            "root_meaning",
            "root_base",
            "construction",
            "derivative",
            "suffix",
            "phonetic",
            "compound_type",
            "compound_construction",
            "source_1",
            "sutta_1",
            "example_1",
            "source_2",
            "sutta_2",
            "example_2",
            "antonym",
            "synonym",
            "variant",
            "commentary",
            "notes",
            "sbs_notes",
            "link",
            "audio",
            "test",
            "feedback",
            "marks",
        ],
    },
    "Roots Pali Class": {
        "model_name": "Roots Class",
        "fields": [
            "id",
            "pali",
            "sbs_class_anki",
            "grammar",
            "neg",
            "verb",
            "trans",
            "plus_case",
            "meaning",
            "meaning_lit",
            "native",
            "sanskrit",
            "sanskrit_root",
            "sanskrit_root_meaning",
            "sanskrit_root_class",
            "root",
            "root_has_verb",
            "root_group",
            "root_sign",
            "root_meaning",
            "root_base",
            "construction",
            "derivative",
            "suffix",
            "phonetic",
            "compound_type",
            "compound_construction",
            "source_1",
            "sutta_1",
            "example_1",
            "source_2",
            "sutta_2",
            "example_2",
            "antonym",
            "synonym",
            "variant",
            "commentary",
            "notes",
            "sbs_notes",
            "link",
            "audio",
            "test",
            "feedback",
            "marks",
        ],
    },
    "SBS Pali-English Vocab": {
        "model_name": "SBS Vocab",
        "fields": [
            "id",
            "pali",
            "grammar",
            "neg",
            "verb",
            "trans",
            "plus_case",
            "meaning",
            "meaning_lit",
            "native",
            "sbs_meaning",
            "sanskrit",
            "sanskrit_root",
            "sanskrit_root_meaning",
            "sanskrit_root_class",
            "root",
            "root_has_verb",
            "root_group",
            "root_sign",
            "root_meaning",
            "root_base",
            "construction",
            "derivative",
            "suffix",
            "phonetic",
            "compound_type",
            "compound_construction",
            "sbs_source_1",
            "sbs_sutta_1",
            "sbs_example_1",
            "sbs_chant_pali_1",
            "sbs_chant_eng_1",
            "sbs_chapter_1",
            "sbs_source_2",
            "sbs_sutta_2",
            "sbs_example_2",
            "sbs_chant_pali_2",
            "sbs_chant_eng_2",
            "sbs_chapter_2",
            "antonym",
            "synonym",
            "variant",
            "commentary",
            "notes",
            "sbs_notes",
            "link",
            "sbs_index",
            "audio",
            "test",
            "feedback",
            "marks",
        ],
    },
    "Suttas Advanced Pali Class": {
        "model_name": "Advanced Suttas",
        "fields": [
            "id",
            "pali",
            "grammar",
            "neg",
            "verb",
            "trans",
            "plus_case",
            "meaning",
            "meaning_lit",
            "native",
            "sanskrit",
            "sanskrit_root",
            "sanskrit_root_meaning",
            "sanskrit_root_class",
            "root",
            "root_has_verb",
            "root_group",
            "root_sign",
            "root_meaning",
            "root_base",
            "construction",
            "derivative",
            "suffix",
            "phonetic",
            "compound_type",
            "compound_construction",
            "source",
            "sutta",
            "example",
            "antonym",
            "synonym",
            "variant",
            "commentary",
            "notes",
            "sbs_notes",
            "link",
            "audio",
            "test",
            "feedback",
            "marks",
        ],
    },
    "Vocab Pali Class": {
        "model_name": "pali class Vocab",
        "fields": [
            "id",
            "pali",
            "sbs_class_anki",
            "grammar",
            "neg",
            "verb",
            "trans",
            "plus_case",
            "meaning",
            "meaning_lit",
            "native",
            "sanskrit",
            "sanskrit_root",
            "sanskrit_root_meaning",
            "sanskrit_root_class",
            "root",
            "root_has_verb",
            "root_group",
            "root_sign",
            "root_meaning",
            "root_base",
            "construction",
            "derivative",
            "suffix",
            "phonetic",
            "compound_type",
            "compound_construction",
            "source",
            "sutta",
            "example",
            "example_translation",
            "extra",
            "antonym",
            "synonym",
            "variant",
            "commentary",
            "notes",
            "sbs_notes",
            "link",
            "audio",
            "test",
            "feedback",
            "marks",
        ],
    },
    "Пали Словарь": {
        "model_name": "Pāli",
        "fields": [
            "id",
            "pali",
            "grammar",
            "neg",
            "verb",
            "trans",
            "plus_case",
            "meaning",
            "meaning_lit",
            "ru_meaning",
            "ru_meaning_lit",
            "sbs_meaning",
            "sanskrit",
            "sanskrit_root",
            "sanskrit_root_meaning",
            "sanskrit_root_ru_meaning",
            "sanskrit_root_class",
            "root",
            "root_has_verb",
            "root_group",
            "root_sign",
            "root_meaning",
            "root_ru_meaning",
            "root_base",
            "construction",
            "derivative",
            "suffix",
            "phonetic",
            "compound_type",
            "compound_construction",
            "source_1",
            "sutta_1",
            "example_1",
            "source_2",
            "sutta_2",
            "example_2",
            "antonym",
            "synonym",
            "variant",
            "commentary",
            "notes",
            "sbs_notes",
            "ru_notes",
            "link",
            "audio",
            "test",
            "feedback",
            "marks",
        ],
    },
}

DECKS: list[DeckSpec] = [
    DeckSpec(
        deck_name="Common Roots",
        model_name="common roots",
        csv_path_attr="pali_class/common_roots.csv",
        slug="common_roots",
        source="csv",
        field_map={
            "root": lambda row: row.get("root", ""),
            "root_clean": lambda row: row.get("root_clean", ""),
            "sanskrit_root": lambda row: row.get("sanskrit_root", ""),
            "root_group": lambda row: row.get("root_group", ""),
            "root_sign": lambda row: row.get("root_sign", ""),
            "root_meaning": lambda row: row.get("root_meaning", ""),
            "main_verb": lambda row: row.get("main_verb", ""),
            "examples": lambda row: row.get("examples", ""),
            "native": lambda row: row.get("native", ""),
            "test": lambda row: row.get("test", ""),
            "feedback": lambda row: row.get("feedback", ""),
        },
    ),
    DeckSpec(
        deck_name="Grammar Pali Class",
        model_name="pali class abbrev",
        csv_path_attr="grammar",
        slug="grammar_pali_class",
        source="csv",
        creates_new_notes=True,
        field_map={
            "id": lambda row: str(row.get("id", "")),
            "abbrev": lambda row: row.get("abbrev", ""),
            "meaning": lambda row: row.get("meaning", ""),
            "pali": lambda row: row.get("pali", ""),
            "example": lambda row: row.get("example", ""),
            "explanation": lambda row: row.get("explanation", ""),
            "type": lambda row: row.get("type", ""),
            "feedback": lambda row: row.get("feedback", ""),
            "test": lambda row: row.get("test", ""),
            # For other models, fields will be mapped if they exist in row
            "gramma": lambda row: row.get("gramma", ""),
            "of": lambda row: row.get("of", ""),
            "eng": lambda row: row.get("eng", ""),
            "related": lambda row: row.get("related", ""),
            "decl-con": lambda row: row.get("decl-con", ""),
            "pattern": lambda row: row.get("pattern", ""),
            "native": lambda row: row.get("native", ""),
            "sandhi": lambda row: row.get("sandhi", ""),
            "details": lambda row: row.get("details", ""),
            "result": lambda row: row.get("result", ""),
            "meeting": lambda row: row.get("meeting", ""),
        },
    ),
    DeckSpec(
        deck_name="Pali Bhikkhu Vibhanga",
        model_name="Vibhanga",
        csv_path_attr="anki_vibhanga.csv",
        slug="pali_bhikkhu_vibhanga",
        source="db",
        field_map={
            **_base_db_fields(),
            "source": lambda i: _to_br(i.sbs.vib_source) if i.sbs else "",
            "sutta": lambda i: _to_br(i.sbs.vib_sutta) if i.sbs else "",
            "example": lambda i: _to_br(i.sbs.vib_example) if i.sbs else "",
            "feedback": lambda i: get_feedback(i, "vibhanga"),
        },
    ),
    DeckSpec(
        deck_name="Pali DHP vocab",
        model_name="DHP Vocab",
        csv_path_attr="anki_dhp.csv",
        slug="pali_dhp_vocab",
        source="db",
        field_map={
            **_base_db_fields(),
            "source": lambda i: _to_br(i.sbs.dhp_source) if i.sbs else "",
            "sutta": lambda i: _to_br(i.sbs.dhp_sutta) if i.sbs else "",
            "example": lambda i: _to_br(i.sbs.dhp_example) if i.sbs else "",
            "feedback": lambda i: get_feedback(i, "dhp"),
        },
    ),
    DeckSpec(
        deck_name="Pali Parittas",
        model_name="Paritta",
        csv_path_attr="anki_parittas.csv",
        slug="pali_parittas",
        source="db",
        field_map={
            "id": lambda i: str(i.id),
            "pali": lambda i: i.lemma_1,
            "grammar": lambda i: i.grammar,
            "meaning": lambda i: i.meaning_1 or i.meaning_2,
            "meaning_lit": lambda i: i.meaning_lit,
            "root": get_root_key,
            "root_group": lambda i: str(i.rt.root_group) if i.rt else "",
            "root_sign": lambda i: i.root_sign if i.rt else "",
            "root_meaning": lambda i: i.rt.root_meaning if i.rt else "",
            "root_base": lambda i: i.root_base if i.rt else "",
            "construction": get_construction,
            "source": lambda i: get_paritta_source(i)[0],
            "sutta": lambda i: get_paritta_source(i)[1],
            "example": lambda i: get_paritta_source(i)[2],
            "audio": lambda i: _SBS_TOOLS.generate_sbs_audio(i.lemma_clean),
            "test": lambda i: current_date,
            "feedback": lambda i: get_feedback(i, "paritta"),
        },
    ),
    DeckSpec(
        deck_name="Pali Patimokkha Word By Word",
        model_name="Pātimokkha word by word",
        csv_path_attr="anki_patimokkha.csv",
        slug="pali_patimokkha_word_by_word",
        source="csv",
        field_map={
            "pali": lambda row: row.get("pali", ""),
            "pos": lambda row: row.get("pos", ""),
            "grammar": lambda row: row.get("grammar", ""),
            "case": lambda row: row.get("case", ""),
            "native": lambda row: row.get("native", ""),
            "meaning": lambda row: row.get("meaning", ""),
            "meaning_lit": lambda row: row.get("meaning_lit", ""),
            "root": lambda row: row.get("root", ""),
            "root_gp": lambda row: row.get("root_gp", ""),
            "root_sign": lambda row: row.get("root_sign", ""),
            "base": lambda row: row.get("base", ""),
            "construction": lambda row: row.get("construction", ""),
            "compound_type": lambda row: row.get("compound_type", ""),
            "compound_construction": lambda row: row.get("compound_construction", ""),
            "variant": lambda row: row.get("variant", ""),
            "abbrev": lambda row: row.get("abbrev", ""),
            "source": lambda row: row.get("source", ""),
            "sentence": lambda row: row.get("sentence", ""),
            "commentary": lambda row: row.get("commentary", ""),
            "test": lambda row: row.get("test", ""),
            "order": lambda row: row.get("order", ""),
            "feedback": lambda row: row.get("feedback", ""),
            "web_link": lambda row: row.get("web_link", ""),
            "notez": lambda row: row.get("notez", ""),
        },
    ),
    DeckSpec(
        deck_name="Phonetic Changes Pali Class",
        model_name="Phonetic Class",
        csv_path_attr="pali_class/phonetic_class.csv",
        slug="phonetic_changes_pali_class",
        source="db",
        field_map={
            **_base_db_fields(),
            "sbs_class_anki": lambda i: str(i.sbs.class_anki) if i.sbs else "",
            "source_1": lambda i: get_example_for_class(i)[0],
            "sutta_1": lambda i: get_example_for_class(i)[1],
            "example_1": lambda i: get_example_for_class(i)[2],
            "source_2": lambda i: "",
            "sutta_2": lambda i: "",
            "example_2": lambda i: "",
            "sbs_notes": lambda i: _to_br(i.sbs.sbs_notes) if i.sbs else "",
            "feedback": lambda i: get_feedback(i, "root-phonetic"),
        },
    ),
    DeckSpec(
        deck_name="Roots Pali Class",
        model_name="Roots Class",
        csv_path_attr="pali_class/roots_class.csv",
        slug="roots_pali_class",
        source="db",
        field_map={
            **_base_db_fields(),
            "sbs_class_anki": lambda i: str(i.sbs.class_anki) if i.sbs else "",
            "source_1": lambda i: get_example_for_class(i)[0],
            "sutta_1": lambda i: get_example_for_class(i)[1],
            "example_1": lambda i: get_example_for_class(i)[2],
            "source_2": lambda i: "",
            "sutta_2": lambda i: "",
            "example_2": lambda i: "",
            "sbs_notes": lambda i: _to_br(i.sbs.sbs_notes) if i.sbs else "",
            "feedback": lambda i: get_feedback(i, "root-phonetic"),
        },
    ),
    DeckSpec(
        deck_name="SBS Pali-English Vocab",
        model_name="SBS Vocab",
        csv_path_attr="anki_sbs.csv",
        slug="sbs_pali_english_vocab",
        source="db",
        updates_tags=True,
        field_map={
            **_base_db_fields(),
            "sbs_meaning": lambda i: i.sbs.sbs_meaning if i.sbs else "",
            "sbs_source_1": lambda i: _to_br(i.sbs.sbs_source_1) if i.sbs else "",
            "sbs_sutta_1": lambda i: _to_br(i.sbs.sbs_sutta_1) if i.sbs else "",
            "sbs_example_1": lambda i: _to_br(i.sbs.sbs_example_1) if i.sbs else "",
            "sbs_chant_pali_1": lambda i: i.sbs.sbs_chant_pali_1 if i.sbs else "",
            "sbs_chant_eng_1": lambda i: i.sbs.sbs_chant_eng_1 if i.sbs else "",
            "sbs_chapter_1": lambda i: str(i.sbs.sbs_chapter_1) if i.sbs else "",
            "sbs_source_2": lambda i: _to_br(i.sbs.sbs_source_2) if i.sbs else "",
            "sbs_sutta_2": lambda i: _to_br(i.sbs.sbs_sutta_2) if i.sbs else "",
            "sbs_example_2": lambda i: _to_br(i.sbs.sbs_example_2) if i.sbs else "",
            "sbs_chant_pali_2": lambda i: i.sbs.sbs_chant_pali_2 if i.sbs else "",
            "sbs_chant_eng_2": lambda i: i.sbs.sbs_chant_eng_2 if i.sbs else "",
            "sbs_chapter_2": lambda i: str(i.sbs.sbs_chapter_2) if i.sbs else "",
            "sbs_notes": lambda i: _to_br(i.sbs.sbs_notes) if i.sbs else "",
            "sbs_index": lambda i: str(i.sbs.sbs_index) if i.sbs else "",
            "feedback": lambda i: get_feedback(i, "sbs"),
        },
    ),
    DeckSpec(
        deck_name="Suttas Advanced Pali Class",
        model_name="Advanced Suttas",
        csv_path_attr="pali_class/suttas_class.csv",
        slug="suttas_advanced_pali_class",
        source="db",
        field_map={
            **_base_db_fields(),
            "source": lambda i: _to_br(i.sbs.discourses_source) if i.sbs else "",
            "sutta": lambda i: _to_br(i.sbs.discourses_sutta) if i.sbs else "",
            "example": lambda i: _to_br(i.sbs.discourses_example) if i.sbs else "",
            "sbs_notes": lambda i: _to_br(i.sbs.sbs_notes) if i.sbs else "",
            "feedback": lambda i: get_feedback(i, "suttas"),
        },
    ),
    DeckSpec(
        deck_name="Vocab Pali Class",
        model_name="pali class Vocab",
        csv_path_attr="pali_class/class_all.csv",
        slug="vocab_pali_class",
        source="db",
        field_map={
            **_base_db_fields(),
            "sbs_class_anki": lambda i: str(i.sbs.class_anki) if i.sbs else "",
            "source": lambda i: get_example_for_class(i)[0],
            "sutta": lambda i: get_example_for_class(i)[1],
            "example": lambda i: get_example_for_class(i)[2],
            "example_translation": lambda i: (
                i.sbs.class_example_translation if i.sbs else ""
            ),
            "extra": lambda i: i.sbs.class_extra if i.sbs else "",
            "sbs_notes": lambda i: _to_br(i.sbs.sbs_notes) if i.sbs else "",
            "feedback": lambda i: get_feedback(i, "class"),
        },
    ),
    DeckSpec(
        deck_name="Пали Словарь",
        model_name="Pāli",
        csv_path_attr="anki_dps.csv",
        slug="pali_slovar",
        source="db",
        field_map={
            **_base_db_fields(),
            "ru_meaning": lambda i: i.ru.ru_meaning if i.ru else "",
            "ru_meaning_lit": lambda i: i.ru.ru_meaning_lit if i.ru else "",
            "sbs_meaning": lambda i: i.sbs.sbs_meaning if i.sbs else "",
            "sanskrit_root_ru_meaning": lambda i: (
                i.rt.sanskrit_root_ru_meaning if i.rt else ""
            ),
            "root_ru_meaning": lambda i: i.rt.root_ru_meaning if i.rt else "",
            "source_1": lambda i: _to_br(i.source_1),
            "sutta_1": lambda i: _to_br(i.sutta_1),
            "example_1": lambda i: _to_br(i.example_1),
            "source_2": lambda i: _to_br(i.source_2),
            "sutta_2": lambda i: _to_br(i.sutta_2),
            "example_2": lambda i: _to_br(i.example_2),
            "sbs_notes": lambda i: _to_br(i.sbs.sbs_notes) if i.sbs else "",
            "ru_notes": lambda i: _to_br(i.ru.ru_notes) if i.ru else "",
            "feedback": lambda i: get_feedback(i, "dps"),
        },
    ),
]
