"""Centralized lists of DPS fields for different views and filters."""

"""
"dps_id"
"dps_lemma_1"
"dps_grammar"
"dps_meaning"
"dps_suggestion"
"dps_ru_meaning"
"dps_ru_meaning_lit"
"dps_ru_cognate"
"dps_sbs_meaning"
"dps_root"
"dps_constriction"
"dps_synonym_antonym"
"dps_notes"
"dps_notes_suggestion"
"dps_ru_notes"
"dps_sbs_notes"
"dps_source_1"
"dps_sutta_1"
"dps_example_1"
"dps_source_2"
"dps_sutta_2"
"dps_example_2"
"dps_sbs_source_1"
"dps_sbs_sutta_1"
"dps_sbs_example_1"
"dps_sbs_chant_pali_1"
"dps_sbs_chant_eng_1"
"dps_sbs_chapter_1"
"dps_sbs_source_2"
"dps_sbs_sutta_2"
"dps_sbs_example_2"
"dps_sbs_chant_pali_2"
"dps_sbs_chant_eng_2"
"dps_sbs_chapter_2"
"dps_dhp_source"
"dps_dhp_sutta"
"dps_dhp_example"
"dps_pat_source"
"dps_pat_sutta"
"dps_pat_example"
"dps_vib_source"
"dps_vib_sutta"
"dps_vib_example"
"dps_class_source"
"dps_class_sutta"
"dps_class_example"
"dps_class_example_translation"
"dps_discourses_source"
"dps_discourses_sutta"
"dps_discourses_example"
"dps_extra_source"
"dps_extra_sutta"
"dps_extra_example"
"dps_sbs_class_anki"
"dps_sbs_class"
"dps_sbs_category"
"dps_sbs_patimokkha"
"""

ALL_DPS = [
    "dps_id",
    "dps_lemma_1",
    "dps_grammar",
    "dps_meaning",
    "dps_suggestion",
    "dps_ru_meaning",
    "dps_ru_meaning_lit",
    "dps_ru_cognate",
    "dps_sbs_meaning",
    "dps_root",
    "dps_constriction",
    "dps_synonym_antonym",
    "dps_notes",
    "dps_notes_suggestion",
    "dps_ru_notes",
    "dps_sbs_notes",
    "dps_source_1",
    "dps_sutta_1",
    "dps_example_1",
    "dps_source_2",
    "dps_sutta_2",
    "dps_example_2",
    "dps_sbs_source_1",
    "dps_sbs_sutta_1",
    "dps_sbs_example_1",
    "dps_sbs_chant_pali_1",
    "dps_sbs_chant_eng_1",
    "dps_sbs_chapter_1",
    "dps_sbs_source_2",
    "dps_sbs_sutta_2",
    "dps_sbs_example_2",
    "dps_sbs_chant_pali_2",
    "dps_sbs_chant_eng_2",
    "dps_sbs_chapter_2",
    "dps_dhp_source",
    "dps_dhp_sutta",
    "dps_dhp_example",
    "dps_pat_source",
    "dps_pat_sutta",
    "dps_pat_example",
    "dps_vib_source",
    "dps_vib_sutta",
    "dps_vib_example",
    "dps_class_source",
    "dps_class_sutta",
    "dps_class_example",
    "dps_class_example_translation",
    "dps_discourses_source",
    "dps_discourses_sutta",
    "dps_discourses_example",
    "dps_extra_source",
    "dps_extra_sutta",
    "dps_extra_example",
    "dps_sbs_class_anki",
    "dps_sbs_class",
    "dps_sbs_category",
    "dps_sbs_patimokkha"
]


VIB_FIELDS = [
    "dps_id",
    "dps_lemma_1",
    "dps_grammar",
    "dps_meaning",
    "dps_suggestion",
    "dps_ru_meaning",
    "dps_ru_meaning_lit",
    "dps_ru_cognate",
    "dps_sbs_meaning",
    "dps_root",
    "dps_constriction",
    "dps_synonym_antonym",
    "dps_notes",
    "dps_notes_suggestion",
    "dps_ru_notes",
    "dps_sbs_notes",
    "dps_source_1",
    "dps_sutta_1",
    "dps_example_1",
    "dps_source_2",
    "dps_sutta_2",
    "dps_example_2",
    "dps_vib_source",
    "dps_vib_sutta",
    "dps_vib_example",
    "dps_sbs_patimokkha"
]
