#!/bin/bash

# This script is used to copy DPD files to the server.
# It first checks if the user wants to mount the fileserver,
# and finally unzips and copies the files to the appropriate directories.

# Ask the user if they want to attempt to mount the fileserver
while true; do
    echo -ne "\033[1;34m Do you want to attempt to mount the fileserver? \033[0m"
    read mount_confirm
    case $mount_confirm in
        [Yy]* )
            mnt
            break;;
        * )
            break;;
    esac
done

cd "$HOME/Documents/dpd-db"

# Ask to push DPD-SBS
while true; do
    echo -ne "\033[1;34m DPD-SBS to the server? \033[0m"
    read -n 1 -s yn
    if [[ $yn == "q" ]]; then
        echo -e "\n\033[1;31m Aborted by user.\033[0m"
        exit 1
    fi
    case $yn in
        [Yy]* )
            echo -e "\033[1;33m copying DPD-SBS...\033[0m"
            scripts/moving/copy_dpdsbs_from_sbs2filesrv.py
            break;;
        * )
            break;;
    esac
done

# Ask to push RU DPD
while true; do
    echo -ne "\033[1;34m RU-DPD to the server?\033[0m"
    read -n 1 -s yn
    if [[ $yn == "q" ]]; then
        echo -e "\n\033[1;31m Aborted by user.\033[0m"
        exit 1
    fi
    case $yn in
        [Yy]* )
            echo -e "\033[1;33m copying ru-dpd.\033[0m"
            scripts/moving/copy_rudpd_from_share2filesrv.py
            break;;
        * )
            break;;
    esac
done

cd

# Ask the user if they want to attempt to umount the fileserver
while true; do
    echo -ne "\033[1;34m Do you want to umount the fileserver? \033[0m"
    read -n 1 -s mount_confirm
    if [[ $mount_confirm == "q" ]]; then
        echo -e "\n\033[1;31m Aborted by user.\033[0m"
        exit 1
    fi
    case $mount_confirm in
        [Yy]* )
            umnt
            break;;
        * )
            break;;
    esac
done