name: Russian Build mkdocs site and copy to repo

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["sbs-ru"]
    paths:
      - 'docs_rus/**'
      - 'mkdocs_ru.yaml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: read # Keep only read for checkout

# Concurrency block removed

jobs:
  deploy:
    # Environment block removed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install MkDocs dependencies
        run: uv pip install --system mkdocs mkdocs-material PyYAML
      
      - name: Populate index folders
        run: |
          uv run python3 scripts/rus_exporter/docs_add_indexes.py

      - name: Update CSS Variables
        run: uv run python3 scripts/build/docs_update_css.py

      - name: Build MkDocs site
        run: mkdocs build

      - name: Configure SSH for Org Repo
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DPD_DEPLOY_KEY }}

      - name: Push to Devamitta/dpd.rus.git
        run: |
          # Setup git identity
          git config --global user.name "DPD Bot"
          git config --global user.email "dpdbot@example.com"

          # Clone and sync site files
          git clone git@github.com:Devamitta/dpd.rus.git dest_repo
          cd dest_repo
          rsync -a --delete --exclude='.git' --exclude='.github' "$GITHUB_WORKSPACE/docs_site/" .
          
          # Commit and push if changes exist
          git add -A
          git diff --quiet && git diff --cached --quiet || \
            (git commit -m "Update site: $(date +'%Y-%m-%d %H:%M:%S')" && git push origin HEAD:ru)
